User.create!([
  {first_name: "Jocelyn", last_name: "Moya", email: "je@gmail.com", password_digest: "password", password_confirmation:"password"}
])
Board.create!([
  {user_id: 1, context: "daily"},
  {user_id: 1, context: "food"},
  {user_id: 1, context: "clothing"},
  {user_id: 1, context: "hygiene"},
  {user_id: 1, context: "activities"},
  {user_id: 1, context: "family"}
])



BoardWord.create!([
  {word_id: 1, board_id: 1},
  {word_id: 1, board_id: 2},
  {word_id: 1, board_id: 3},
  {word_id: 1, board_id: 4},
  {word_id: 1, board_id: 5},
  {word_id: 1, board_id: 6},
  {word_id: 2, board_id: 1},
  {word_id: 2, board_id: 2},
  {word_id: 2, board_id: 3},
  {word_id: 2, board_id: 4},
  {word_id: 2, board_id: 5},
  {word_id: 2, board_id: 6},
  {word_id: 3, board_id: 1},
  {word_id: 3, board_id: 2},
  {word_id: 3, board_id: 3},
  {word_id: 3, board_id: 4},
  {word_id: 3, board_id: 5},
  {word_id: 3, board_id: 6},
  {word_id: 4, board_id: 1},
  {word_id: 4, board_id: 2},
  {word_id: 4, board_id: 6},
  {word_id: 11, board_id: 2},
  {word_id: 13, board_id: 2},
  {word_id: 15, board_id: 2},
  {word_id: 16, board_id: 2},
  {word_id: 18, board_id: 2},
  {word_id: 18, board_id: 1},
  {word_id: 18, board_id: 3},
  {word_id: 18, board_id: 4},
  {word_id: 18, board_id: 5},
  {word_id: 19, board_id: 1},
  {word_id: 19, board_id: 3},
  {word_id: 19, board_id: 4},
  {word_id: 19, board_id: 5},
  {word_id: 19, board_id: 2},
  {word_id: 20, board_id: 5},
  {word_id: 21, board_id: 2},
  {word_id: 22, board_id: 1},
  {word_id: 23, board_id: 1},
  {word_id: 24, board_id: 4},
  {word_id: 24, board_id: 1},
  {word_id: 25, board_id: 4},
  {word_id: 26, board_id: 4},
  {word_id: 27, board_id: 4},
  {word_id: 28, board_id: 4},
  {word_id: 29, board_id: 3},
  {word_id: 30, board_id: 4},
  {word_id: 32, board_id: 5},
  {word_id: 33, board_id: 5},
  {word_id: 41, board_id: 1},
  {word_id: 41, board_id: 5},
  {word_id: 42, board_id: 5},
  {word_id: 43, board_id: 5},
  {word_id: 44, board_id: 5},
  {word_id: 19, board_id: 6},
  {word_id: 34, board_id: 6},
  {word_id: 35, board_id: 6},
  {word_id: 36, board_id: 6},
  {word_id: 37, board_id: 6},
  {word_id: 38, board_id: 6},
  {word_id: 39, board_id: 6},
  {word_id: 40, board_id: 6},
  {word_id: 45, board_id: 1},
  {word_id: 46, board_id: 1},
  {word_id: 47, board_id: 3},
  {word_id: 48, board_id: 3},
  {word_id: 49, board_id: 3},
  {word_id: 50, board_id: 3},
  {word_id: 51, board_id: 3},
  {word_id: 52, board_id: 3},
  {word_id: 53, board_id: 2},
  {word_id: 54, board_id: 2}
])

